services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  main:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      CLIENT_URL: ${CLIENT_URL}
      HOST: ${HOST}
      LANGUAGE: ${LANGUAGE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID : ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET_KEY : ${GOOGLE_SECRET_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_KEY: ${OPENAI_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://rabbitmq:5672}
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
      - /app/node_modules

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      CLIENT_URL: ${CLIENT_URL}
      HOST: ${HOST}
      LANGUAGE: ${LANGUAGE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_KEY: ${OPENAI_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://rabbitmq:5672}
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
      - /app/node_modules
    deploy:
      replicas: 1

volumes:
  rabbitmq_data:
